"""init

Revision ID: 467d77868b45
Revises: 7f99edbd4cc6
Create Date: 2022-08-30 15:24:09.742920

"""

# revision identifiers, used by Alembic.
revision = '467d77868b45'
down_revision = '7f99edbd4cc6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
