"""init

Revision ID: 69e746cf6e70
Revises: dd33cb03d01f
Create Date: 2022-08-30 15:09:26.425254

"""

# revision identifiers, used by Alembic.
revision = '69e746cf6e70'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
