"""init

Revision ID: 7f99edbd4cc6
Revises: 69e746cf6e70
Create Date: 2022-08-30 15:11:12.242882

"""

# revision identifiers, used by Alembic.
revision = '7f99edbd4cc6'
down_revision = '69e746cf6e70'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
